config/routes.php
<?php

/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    $routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Users', 'action' => 'login']);

    $routes->connect('/logout', ['controller' => 'Users', 'action' => 'logout']);

    $routes->connect('/register', ['controller' => 'Users', 'action' => 'register']);
    
    $routes->connect('/profile', ['controller' => 'Users', 'action' => 'index']);

    $routes->connect('/forgot-password', ['controller' => 'Users', 'action' => 'forgotPassword']);

    $routes->connect('/reset/*', ['controller' => 'Users', 'action' => 'reset']);

    $routes->connect('/activateEmail/*', ['controller' => 'Users', 'action' => 'activateByEmail']);

    $routes->connect('/stream/index/*', ['controller' => 'Dashboard', 'action' => 'stream']);
    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
//    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Table/StreamsTable.php
<?php

namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;
use Cake\Network\Session;
use Cake\Routing\Router;
use Cake\Auth\DefaultPasswordHasher;

/**
 * Streams Model
 *
 * @property \App\Model\Table\UsersTable&\Cake\ORM\Association\BelongsTo $Users
 * @property \App\Model\Table\StreamDetailsTable&\Cake\ORM\Association\HasMany $StreamDetails
 *
 * @method \App\Model\Entity\Stream get($primaryKey, $options = [])
 * @method \App\Model\Entity\Stream newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Stream[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Stream|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Stream saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Stream patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Stream[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Stream findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class StreamsTable extends Table {

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config) {
        parent::initialize($config);

        $this->setTable('streams');
        $this->setDisplayField('title');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Users', [
            'foreignKey' => 'user_id',
            'joinType' => 'INNER',
        ]);
        $this->hasOne('Notifications', [
            'foreignKey' => 'stream_id',
            'joinType' => 'LEFT',
        ]);
        $this->hasMany('StreamDetails', [
            'foreignKey' => 'stream_id',
            'joinType' => 'LEFT',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator) {
        $validator
                ->integer('id')
                ->allowEmptyString('id', null, 'create');

        $validator
                ->scalar('title')
                ->maxLength('title', 255)
                ->requirePresence('title', 'create')
                ->notEmptyString('title');
        
        $validator
                ->scalar('description')
                ->requirePresence('description', 'create')
                ->notEmptyString('description');

        $validator
                ->dateTime('start_time')
                ->requirePresence('start_time', 'create')
                ->notEmptyDateTime('start_time');
        $validator
                ->dateTime('end_time')
                ->requirePresence('end_time', 'create')
                ->notEmptyDateTime('end_time');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules) {
        $rules->add($rules->existsIn(['user_id'], 'Users'));

        return $rules;
    }

    protected function _insert($entity, $data) {
        $session = new Session();
        $userId = $session->read('Auth.User.id');
        $data['user_id'] = $userId;
        $data['ip_address'] = Router::getRequest()->clientIp();
        $data['request_token'] = (new DefaultPasswordHasher)->hash(date('Y-m-d'));
        $data['verify_token'] = (new DefaultPasswordHasher)->hash($userId);
        return parent::_insert($entity, $data);
    }

}

src/Template/Element/footer.ctp
<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>
<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <?= $this->Html->link('Logout', 'logout', ['class' => 'btn btn-primary']) ?>
            </div>
        </div>
    </div>
</div>

src/Template/Element/navigation.ctp
<!-- Top bar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <div class="users">
        <i class="fa fa-users"></i>
        <?= $liveUser ?>
    </div>
    <!-- Side bar Toggle (Top bar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
    <!-- Top bar Navigation bar -->
    <ul class="navbar-nav ml-auto">
        <!--<div class="topbar-divider d-none d-sm-block"></div>-->
        <!-- Navigation Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="/profile" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <!--<span class="mr-2 d-none d-lg-inline text-gray-600 small"><?= $Auth->user('username') ?></span>-->
                <!--<i class="fa fa-user fa-lg"></i>-->
                <?= $this->Html->image('profile_image/' . $Auth->user('profile_image'), ['height' => '30', 'class' => 'rounded-circle']) ?>
            </a>
            <!-- Drop down - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" style="z-index: 99999999;" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="/profile">
                    <?= $Auth->user('name') ?>
                    <br>
                    <?= $Auth->user('email') ?>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>
    </ul>
</nav>
<!-- End of Top bar -->

src/Template/Element/sidebar.ctp
<!-- Side bar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion <?= isset($toggled) && $toggled ? 'toggled' : '' ?>" id="accordionSidebar">

    <!-- Side bar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<?= $this->Url->build(['controller' => 'Dashboard', 'action' => 'index']) ?>">
        <div class="sidebar-brand-icon">
            <?= $this->Html->image('logo.png', ['height' => '100']) ?>
        </div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Navigation Item - Dashboard -->
    <li class="nav-item">

        <?=
        $this->Html->link('<i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>', [
            'controller' => 'Dashboard',
            'action' => 'index'
                ], [
            'class' => 'nav-link',
            'escape' => false]
        )
        ?>
    </li>

    <li class="nav-item">

        <?=
        $this->Html->link('<i class="fas fa-fw fa-user-alt"></i>
            <span>Profile</span></a>', [
            'controller' => 'Profile',
            'action' => 'index'
                ], [
            'class' => 'nav-link',
            'escape' => false]
        )
        ?>
    </li>


    <li class="nav-item">

        <?=
        $this->Html->link('<i class="fas fa-fw fa-handshake"></i>
            <span>Schedule New Meeting</span></a>', [
            'controller' => 'Streams',
            'action' => 'add'
                ], [
            'class' => 'nav-link',
            'escape' => false]
        )
        ?>
    </li>

    <!-- Navigation Item - Upcoming Meetings -->
    <li class="nav-item">

        <?=
        $this->Html->link('<i class="fas fa-fw fa-handshake"></i>
            <span>Upcoming Meetings</span></a>', [
            'controller' => 'Streams',
            'action' => 'index'
                ], [
            'class' => 'nav-link',
            'escape' => false]
        )
        ?>
    </li>

    <!-- Navigation Item - Friend List -->
    <li class="nav-item">

        <?=
        $this->Html->link('<i class="fas fa-fw fa-handshake"></i>
            <span>Previous Meetings</span></a>', [
            'controller' => 'Streams',
            'action' => 'previous'
                ], [
            'class' => 'nav-link',
            'escape' => false]
        )
        ?>
    </li>

    <!-- Navigation Item - Friend List -->
    <li class="nav-item">

        <?=
        $this->Html->link('<i class="fas fa-fw fa-users"></i>
            <span>My Group</span></a>', [
            'controller' => 'UserFriends',
            'action' => 'index'
                ], [
            'class' => 'nav-link',
            'escape' => false]
        )
        ?>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">


    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->

src/Template/Element/web_socket_1.ctp
<!-- script used to stylize video element -->
<script src="https://www.webrtc-experiment.com/getMediaElement.min.js"></script>

<script src="https://www.webrtc-experiment.com/socket.io.js"></script>
<script src="https://webrtc.github.io/adapter/adapter-latest.js"></script>
<script src="https://www.webrtc-experiment.com/IceServersHandler.js"></script>
<script src="https://www.webrtc-experiment.com/CodecsHandler.js"></script>
<script src="https://www.webrtc-experiment.com/RTCPeerConnection-v1.5.js"></script>
<script src="https://www.webrtc-experiment.com/video-conferencing/conference.js"></script>
<script>
    var config = {
        openSocket: function (config) {
            var SIGNALING_SERVER = 'https://localhost:9559/';

            config.channel = config.channel || '<?= $stream_data->request_token ?>';
//            console.log(config.channel);
            var sender = '<?= $current_user['stream_token'] ?>';
            var email = '<?= $current_user['email'] ?>';
<?php if ($current_user['id'] === $stream_data->user_id) { ?>
                io.connect(SIGNALING_SERVER).emit('new-channel', {
                    channel: config.channel,
                    sender: sender,
                    email: email
                });
<?php } ?>
            setTimeout(function () {
                var socket = io.connect(SIGNALING_SERVER + config.channel);
                console.log(socket);
                console.log(config.channel);
                socket.channel = config.channel;
                socket.on('connect', function () {
                    if (config.callback)
                        config.callback(socket);
                });
                socket.send = function (message) {
                    console.log(message);
                    socket.emit('message', {
                        sender: sender,
                        data: message
                    });
                };
                socket.on('message', config.onmessage);
            }, 3000);
        },
        onRemoteStream: function (media) {
            var mediaElement = getMediaElement(media.video, {width: (videosContainer.clientWidth / 2) - 50,
                buttons: ['mute-audio', 'mute-video', 'full-screen', 'volume-slider']
            });
            mediaElement.id = media.stream.streamid;
            videosContainer.appendChild(mediaElement);
        },
        onRemoteStreamEnded: function (stream, video) {
            if (video.parentNode && video.parentNode.parentNode && video.parentNode.parentNode.parentNode) {
                video.parentNode.parentNode.parentNode.removeChild(video.parentNode.parentNode);
            }
        },
//        onRoomFound: function (room) {
//            var alreadyExist = document.querySelector('button[data-broadcaster="' + room.broadcaster + '"]');
//            if (alreadyExist)
//                return;
//
//            if (typeof roomsList === 'undefined')
//                roomsList = document.body;
//
//            var tr = document.createElement('tr');
//            tr.innerHTML = '<td><strong>' + room.roomName + '</strong> shared a conferencing room with you!</td>' +
//                    '<td><button class="join">Join</button></td>';
//            roomsList.appendChild(tr);
//
//            var joinRoomButton = tr.querySelector('.join');
//            joinRoomButton.setAttribute('data-broadcaster', room.broadcaster);
//            joinRoomButton.setAttribute('data-roomToken', room.roomToken);
//            joinRoomButton.onclick = function () {
//                this.disabled = true;
//
//                var broadcaster = this.getAttribute('data-broadcaster');
//                var roomToken = this.getAttribute('data-roomToken');
//                captureUserMedia(function () {
//                    conferenceUI.joinRoom({
//                        roomToken: roomToken,
//                        joinUser: broadcaster
//                    });
//                }, function () {
//                    joinRoomButton.disabled = false;
//                });
//            };
//        },
//        onRoomClosed: function (room) {
//            var joinButton = document.querySelector('button[data-roomToken="' + room.roomToken + '"]');
//            if (joinButton) {
//                // joinButton.parentNode === <li>
//                // joinButton.parentNode.parentNode === <td>
//                 joinButton.parentNode.parentNode.parentNode === <tr>
//                 joinButton.parentNode.parentNode.parentNode.parentNode === <table>
//                joinButton.parentNode.parentNode.parentNode.parentNode.removeChild(joinButton.parentNode.parentNode.parentNode);
//            }
//        },
        onReady: function () {
            console.log('now you can open or join rooms');
        }
    };
<?php if ($current_user['id'] === $stream_data->user_id) { ?>
        $(document).ready(function () {
            startStream();
        });

        function startStream() {
            captureUserMedia(function () {
                conferenceUI.createRoom({
                    roomName: '<?= $stream_data->title ?>' || 'Anonymous'
                });
            }, function (response) {
                console.log(response);//do later
            });
        }
<?php } else if ($current_user['id'] === $stream_data['stream_detail']->user_id) { ?>
        $(document).ready(function () {
            joinStream();
        });

        function joinStream() {
            var broadcaster = '<?= $stream_data->broadcaster ?>';
            var roomToken = '<?= $stream_data->room_token ?>';
            captureUserMedia(function () {
                conferenceUI.joinRoom({
                    roomToken: roomToken,
                    joinUser: broadcaster
                });
            }, function () {                 //do later
            });
        }
<?php } ?>

    function captureUserMedia(callback, failure_callback) {
        var video = document.createElement('video');
        video.muted = true;
        video.volume = 0;

        try {
            video.setAttributeNode(document.createAttribute('autoplay'));
            video.setAttributeNode(document.createAttribute('playsinline'));
            video.setAttributeNode(document.createAttribute('controls'));
        } catch (e) {
            video.setAttribute('autoplay', true);
            video.setAttribute('playsinline', true);
            video.setAttribute('controls', true);
        }

        getUserMedia({
            video: video,
            onsuccess: function (stream) {
                config.attachStream = stream;

                var mediaElement = getMediaElement(video, {width: (videosContainer.clientWidth / 2) - 50,
                    buttons: ['mute-audio', 'mute-video', 'full-screen', 'volume-slider']
                });
                mediaElement.toggle('mute-audio');
                videosContainer.appendChild(mediaElement);

                callback && callback();
            },
            onerror: function () {
                alert('unable to get access to your webcam');
                callback && callback();
            }
        });
    }
    var conferenceUI = conference(config);

    /* UI specific */
    var videosContainer = document.getElementById('videos-container') || document.body;
//    var btnSetupNewRoom = document.getElementById('setup-new-room');
    var roomsList = document.getElementById('rooms-list');

//    if (btnSetupNewRoom)
//        btnSetupNewRoom.onclick = setupNewRoomButtonClickHandler;

    function rotateVideo(video) {
        video.style[navigator.mozGetUserMedia ? 'transform' : '-webkit-transform'] = 'rotate(0deg)';
        setTimeout(function () {
            video.style[navigator.mozGetUserMedia ? 'transform' : '-webkit-transform'] = 'rotate(360deg)';
        }, 1000);
    }

    function scaleVideos() {
        var videos = document.querySelectorAll('video'),
                length = videos.length, video;

        var minus = 130;
        var windowHeight = 700;
        var windowWidth = 600;
        var windowAspectRatio = windowWidth / windowHeight;
        var videoAspectRatio = 4 / 3;
        var blockAspectRatio;
        var tempVideoWidth = 0;
        var maxVideoWidth = 0;

        for (var i = length; i > 0; i--) {
            blockAspectRatio = i * videoAspectRatio / Math.ceil(length / i);
            if (blockAspectRatio <= windowAspectRatio) {
                tempVideoWidth = videoAspectRatio * windowHeight / Math.ceil(length / i);
            } else {
                tempVideoWidth = windowWidth / i;
            }
            if (tempVideoWidth > maxVideoWidth)
                maxVideoWidth = tempVideoWidth;
        }
        for (var i = 0; i < length; i++) {
            video = videos[i];
            if (video)
                video.width = maxVideoWidth - minus;
        }
    }

    window.onresize = scaleVideos;

</script>